# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kross' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/kidentitymanagement' : '@latest'
    'kde/pim/kimap' : '@latest'
    'kde/pim/kldap' : '@latest'
    'kde/pim/kmailtransport' : '@latest'
    'kde/pim/libkdepim' : '@latest'
    'kde/pim/libkleo' : '@latest'
    'kde/pim/pimcommon' : '@latest'
