# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'kde/pim/akonadi' : '@latest-kf6'
    'kde/pim/akonadi-mime' : '@latest-kf6'
    'kde/pim/kidentitymanagement' : '@latest-kf6'
    'kde/pim/kimap' : '@latest-kf6'
    'kde/pim/kldap' : '@latest-kf6'
    'kde/pim/kmailtransport' : '@latest-kf6'
    'kde/pim/libkleo' : '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
