# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kldap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/libkdepim' : '@same'
    'pim/libkleo' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/kwallet': '@latest'
    'frameworks/kcmutils': '@latest'
    'frameworks/knotifyconfig': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdoctools': '@latest'
    'frameworks/ktexteditor': '@latest'
    'frameworks/kcodecs': '@latest'
    'frameworks/kcrash': '@latest'
    'frameworks/knotifications': '@latest'
    'frameworks/kross': '@latest'
    'frameworks/knewstuff': '@latest'
