# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'kde/pim/akonadi' : '@latest-kf6'
    'kde/pim/akonadi-mime' : '@latest-kf6'
    'kde/pim/kidentitymanagement' : '@latest-kf6'
    'kde/pim/kimap' : '@latest-kf6'
    'kde/pim/kldap' : '@latest-kf6'
    'kde/pim/kmailtransport' : '@latest-kf6'
    'kde/pim/libkdepim' : '@latest-kf6'
    'kde/pim/libkleo' : '@latest-kf6'
    'kde/pim/pimcommon' : '@latest-kf6'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kross' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kimap' : '@same'
    'kde/pim/kldap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/libkleo' : '@same'
    'kde/pim/pimcommon' : '@same'
