# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/akonadi-mime' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kimap' : '@latest-kf6'
    'pim/kldap' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/libkleo' : '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/libkdepim' : '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]      
