# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'pim/akonadi' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kmailtransport' : '@same'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'pim/kmime' : '@same'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
